Accounts.Web/Accounts.Web/Controllers/ChartOfAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Accounts.Data.Accounts;
using Accounts.Domain.Accounts;
using Accounts.Domain.Messaging;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Accounts.Web.Controllers
{
    [Authorize]
    public class ChartOfAccountController : Controller
    {
        DAL_CommonFeatures _dalCommonFeatures = new DAL_CommonFeatures();
        DAL_ChartOfAccount _dalChartOfAccount = new DAL_ChartOfAccount();

        #region DropDown

        public JsonResult GetGroupList()
        {
            var groupList = _dalCommonFeatures.GroupList();

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(groupList, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }

        public JsonResult GetTypeList()
        {
            var typeList = _dalCommonFeatures.TypeList();

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(typeList, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }

        #endregion

        //
        // GET: /ChartOfAccount/
        public JsonResult GetChartOfAccountList()
        {
            var list = _dalChartOfAccount.ChartOfAccountList();

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(list, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }
        public ActionResult Index()
        {
            ViewBag.Title = "ChartOfAccountAdd";
            return View();
        }

        [HttpPost]
        public ActionResult InsertChartOfAccountInfo(ChartOfAccount chart)
        {
            //var list = _dalCompany.AddCompany(company);
            var response = new DBResponse();
            try
            {
                var job = _dalChartOfAccount.InsertChartOfAccount(chart);
                if (job.FirstOrDefault().Id > 0)
                {
                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "200";
                    response.StatusMessage = "Data Insert Successfully";
                }
                else
                {
                    response.Id = -1;
                    response.StatusCode = "501";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }

            }
            catch (Exception ex)
            {
                response.Id = -1;
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        public ActionResult EditView()
        {
            ViewBag.Title = "ChartOfAccountView";
            return View();
        }

        public ActionResult ChartOfAccountEdit()
        {
            return View();
        }
	}
}

Accounts.Web/Accounts.Web/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Accounts.Data.Accounts;
using Accounts.Domain.Accounts;
using Accounts.Domain.Messaging;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Accounts.Web.Controllers
{
    [Authorize]
    public class LoanController : Controller
    {
        DAL_Loan _dalLoan = new DAL_Loan();
        //
        // GET: /Loan/
        public ActionResult Index()
        {
            ViewBag.Title = "EntryLoan";
            return View();
        }

        [HttpPost]
        public ActionResult InsertLoanInfo(LoanBase_t loan)
        {
            var response = new DBResponse();
            try
            {
                var job = _dalLoan.InsertLoanBase_t(loan);

                if (job.Any())
                {
                    if (job.FirstOrDefault().Id > 0)
                    {
                        response.Id = job.FirstOrDefault().Id;
                        response.StatusCode = "200";
                        response.StatusMessage = "Success";
                    }
                    else
                    {
                        response.Id = -1;
                        response.StatusCode = "501";
                        response.StatusMessage = job.FirstOrDefault().StatusMessage;
                    }
                }
                else
                {
                    response.StatusCode = "404";
                    response.StatusMessage = "No available job";
                }
            }
            catch (Exception ex)
            {
                response.Id = -1;
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }

        //
        // View: /Loan/
        public ActionResult LoanView()
        {
            ViewBag.Title = "ViewLoan";
            return View();
        }

        [HttpPost]
        public ActionResult ViewLoanInfo(LoanViewRequest request)
        {
            var response = new LoanViewResponse();
            try
            {
                var job = _dalLoan.LoanInformationView();

                if (job.Any())
                {
                    response.LoanList = job.ToList();
                    response.StatusCode = "200";
                    response.StatusMessage = "Success";
                }
                else
                {
                    response.StatusCode = "404";
                    response.StatusMessage = "No available job";
                }
            }
            catch (Exception ex)
            {
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }
	}
}

Accounts.Web/Accounts.Web/Controllers/VoucherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Accounts.Data.Accounts;
using Accounts.Domain.Accounts;
using Accounts.Domain.Messaging;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Accounts.Web.Controllers
{
    [Authorize]
    public class VoucherController : Controller
    {
        // GET: /Voucher/
        DAL_ChartOfAccount _dalChartOfAccount = new DAL_ChartOfAccount();
        DAL_Ledger _dalLedger = new DAL_Ledger();

        #region DropDown
        public JsonResult GetChartOfAccount()
        {
            var accountList = _dalChartOfAccount.ChartOfAccountList();

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(accountList, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }
        public JsonResult GetCashOfAccount()
        {
            var accountList = _dalLedger.CashOfAccountList();

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(accountList, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }
        #endregion

        #region Journal Voucher

        public JsonResult GetJournalVoucherNo()
        {
            AccountVoucher voucher = new AccountVoucher();

            var list = _dalLedger.GetMaxVoucherNo(1);
            voucher.VoucherNo = list.FirstOrDefault().voucherNo + 1;
            voucher.VoucherType = 1;
            voucher.VoucherName = "JV-0000" + Convert.ToString(voucher.VoucherNo);
            //return voucher.t;

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(voucher, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }
        public ActionResult AddJournal()
        {
            ViewBag.Title = "JournalVoucherAdd";
            return View();
        }
        public ActionResult ViewJournal()
        {
            ViewBag.Title = "JournalVoucherView";
            return View();
        }

        [HttpPost]
        public ActionResult InsertJournalVoucher(LedgerInsertRequest request)
        {
            var response = new DBResponse();
            try
            {
                var job = _dalLedger.InsertLedger(request);
                if (job.FirstOrDefault().Id > 0)
                {
                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "200";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }
                else
                {
                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "501";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }

            }
            catch (Exception ex)
            {
                response.Id = -1;
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Payment Voucher

        public JsonResult GetPaymentVoucherNo()
        {
            AccountVoucher voucher = new AccountVoucher();

            var list = _dalLedger.GetMaxVoucherNo(2);
            voucher.VoucherNo = list.FirstOrDefault().voucherNo + 1;
            voucher.VoucherType = 2;
            voucher.VoucherName = "EV-0000" + Convert.ToString(voucher.VoucherNo);
            //return voucher.t;

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(voucher, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }

        public ActionResult AddPayment()
        {
            ViewBag.Title = "PaymentVoucherAdd";
            return View();
        }
        //public ActionResult ViewPayment()
        //{
        //    ViewBag.Title = "PaymentVoucherView";
        //    return View();
        //}

        [HttpPost]
        public ActionResult InsertPaymentVoucher(VoucherInsertRequest request)
        {
            var ledgerRequest = new LedgerInsertRequest();
            var response = new DBResponse();
            try
            {
                ledgerRequest.ledgerList = request.ledgerList;

                var job = _dalLedger.InsertVoucher(request);
                if (job.FirstOrDefault().Id > 0)
                {
                    _dalLedger.InsertLedger(ledgerRequest);

                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "200";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }
                else
                {
                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "409";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }

            }
            catch (Exception ex)
            {
                response.Id = -1;
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Receipt Voucher

        public JsonResult GetReceiptVoucherNo()
        {
            AccountVoucher voucher = new AccountVoucher();

            var list = _dalLedger.GetMaxVoucherNo(3);
            voucher.VoucherNo = list.FirstOrDefault().voucherNo + 1;
            voucher.VoucherType = 3;
            voucher.VoucherName = "IV-0000" + Convert.ToString(voucher.VoucherNo);
            //return voucher.t;

            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            var result = Json(JsonConvert.SerializeObject(voucher, camelCaseFormatter), JsonRequestBehavior.AllowGet);
            return result;
        }

        public ActionResult AddReceipt()
        {
            ViewBag.Title = "ReceiptVoucherAdd";
            return View();
        }
        public ActionResult ViewReceipt()
        {
            ViewBag.Title = "ReceiptVoucherView";
            return View();
        }

        [HttpPost]
        public ActionResult InsertReceiptVoucher(VoucherInsertRequest request)
        {
            var ledgerRequest = new LedgerInsertRequest();
            var response = new DBResponse();
            try
            {
                ledgerRequest.ledgerList = request.ledgerList;

                var job = _dalLedger.InsertVoucher(request);
                if (job.FirstOrDefault().Id > 0)
                {
                    _dalLedger.InsertLedger(ledgerRequest);

                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "200";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }
                else
                {
                    response.Id = job.FirstOrDefault().Id;
                    response.StatusCode = "409";
                    response.StatusMessage = job.FirstOrDefault().StatusMessage;
                }

            }
            catch (Exception ex)
            {
                response.Id = -1;
                response.StatusCode = "500";
                response.StatusMessage = ex.Message.ToString();
            }
            var camelCaseFormatter = new JsonSerializerSettings();
            camelCaseFormatter.ContractResolver = new CamelCasePropertyNamesContractResolver();
            return Json(JsonConvert.SerializeObject(response, camelCaseFormatter), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Edit/View Voucher
        public ActionResult ViewLedgerList()
        {
            ViewBag.Title = "ViewLedgerList";
            return View();
        }
        public ActionResult GetLedgerList(LedgerListViewRequest request)
        {
            var response = new LedgerListViewResponse();
            try
            {
                var job = _dalLedger.LedgerListForView(request);
                if (job.Any())
                {
                    var jobList = job.GroupBy(x => x.VoucherNo).Select(y => new LedgerListForView
                    {
                        LedgerId = y.FirstOrDefault().LedgerId,
                        TransactionDate = y.FirstOrDefault().TransactionDate,
                        VoucherNo = y.FirstOrDefault().VoucherNo,
                        VoucherType = y.FirstOrDefault().VoucherType,
                        VoucherName = y.FirstOrDefault().VoucherName,
                        Debit = y.Sum(x => x.Debit),
                        Credit = y.Sum(x => x.Credit),
                        Description = y.FirstOrDefault().Description,
                        Narration = y.FirstOrDefault().Narration,

Accounts.Web/Accounts.Web/Views/Shared/--_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>

Accounts.Web/Accounts.Web/Views/Shared/_HeaderLayout.cshtml
@{

}

<div id="header">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="/Home/Index">ERP.<span class="slogan">accounts</span></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon16 icomoon-icon-arrow-4"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            @Html.Partial("_LoginPartial")
            @*<ul class="nav navbar-right usernav">
                <li>
                    <a href="#" class="text-danger avatar">
                        <img src="~/Resources/Template/images/avatar.jpg" alt="" class="image" />
                        <span class="txt" id="loginUserName"></span>
                    </a>
                </li>
                <li><a href="#" id="logOut" onclick="logOut()"><span class="icon16 icomoon-icon-exit"></span><span class="txt"> Logout</span></a></li>
            </ul>*@
        </div><!-- /.nav-collapse -->
    </nav>
</div><!-- End #header -->

Accounts.Web/Accounts.Web/Views/Shared/_MenuList.cshtml
@{

}

<div id="sidebar">

    <div class="sidebar-widget" style="margin: -1px 0 0 0;">
        <h5 class="title" style="margin-bottom:0">Navigation</h5>
    </div><!-- End .sidenav-widget -->
    <div class="mainnav" id="MenuListLoad">
        <ul>
            <li>
                <a class="@{if (ViewBag.Title != null || ViewBag.Title == "Company" || ViewBag.Title == "ChartOfAccountAdd" || ViewBag.Title == "ChartOfAccountView")
                                { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 cut-icon-equalizer"></span>Settings<span class="hasDrop icon16 icomoon-icon-arrow-down-2"></span></a>
                <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "Company" || ViewBag.Title == "ChartOfAccountAdd" || ViewBag.Title == "ChartOfAccountView"))
                                             { <text>display: block;</text>    } else { <text></text>    }}">

                    <li>
                        <a class="@{if (ViewBag.Title != null || ViewBag.Title == "Company")
                                              { <text>Current</text>   } else { <text></text>   }}" href="@Url.Action("Index", "Company")"><span class="icon16 cut-icon-enter"></span>Company</a>
                    </li>
                    <li>
                        <a class="@{if (ViewBag.Title != null || ViewBag.Title == "ChartOfAccountAdd" || ViewBag.Title == "ChartOfAccountView")
                                { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 icomoon-icon-list-2"></span>Chart of Account</a>
                        <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "ChartOfAccountAdd" || ViewBag.Title == "ChartOfAccountView"))
                                             { <text>display: block;</text>    } else { <text></text>    }}">
                            <li>
                                <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ChartOfAccountAdd")
                                { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("Index", "ChartOfAccount")"><span class="icon16 typ-icon-plus"></span>Add Record</a>
                            </li>
                            <li>
                                <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ChartOfAccountView")
                                              { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("EditView", "ChartOfAccount")"><span class="icon16 typ-icon-views"></span>View Record</a>
                            </li>
                        </ul>
                    </li>


                </ul>
            </li>

            <li>
                <a class="@{if (ViewBag.Title != null || ViewBag.Title == "JournalVoucherAdd" || ViewBag.Title == "JournalVoucherView" || ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView"
                                || ViewBag.Title == "ReceiptVoucherAdd" || ViewBag.Title == "ReceiptVoucherView" || ViewBag.Title == "ViewLedgerList")
                          { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 cut-icon-equalizer"></span>Voucher Entry<span class="hasDrop icon16 icomoon-icon-arrow-down-2"></span></a>
                <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "JournalVoucherAdd" || ViewBag.Title == "JournalVoucherView" || ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView"
                                                                       || ViewBag.Title == "ReceiptVoucherAdd" || ViewBag.Title == "ReceiptVoucherView" || ViewBag.Title == "ViewLedgerList"))
                                       { <text>display: block;</text>    } else { <text></text>    }}">
                    <li>
                        <a class="@{if (ViewBag.Title != null || ViewBag.Title == "JournalVoucherAdd" || ViewBag.Title == "JournalVoucherView" || ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView"
                                        || ViewBag.Title == "ReceiptVoucherAdd" || ViewBag.Title == "ReceiptVoucherView")
                                  { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 icomoon-icon-list-2"></span>Add Voucher</a>
                        <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "JournalVoucherAdd" || ViewBag.Title == "JournalVoucherView" || ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView"
                                                                               || ViewBag.Title == "ReceiptVoucherAdd" || ViewBag.Title == "ReceiptVoucherView"))
                                               { <text>display: block;</text>    } else { <text></text>    }}">
                            <li>
                                <a class="@{if (ViewBag.Title != null && ViewBag.Title == "JournalVoucherAdd")
                                          { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("AddJournal", "Voucher")"><span class="icon16 typ-icon-plus"></span>Journal Voucher</a>
                            </li>
                            @*<li>
                                    <a class="@{if (ViewBag.Title != null && ViewBag.Title == "JournalVoucherView")
                                                  { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("ViewJournal", "Voucher")"><span class="icon16 typ-icon-views"></span>View Journal</a>
                                </li>*@
                            <li>
                                <a class="@{if (ViewBag.Title != null && ViewBag.Title == "PaymentVoucherAdd")
                                          { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("AddPayment", "Voucher")"><span class="icon16 typ-icon-plus"></span>Payment Voucher</a>
                            </li>
                            @*<li>
                                    <a class="@{if (ViewBag.Title != null && ViewBag.Title == "PaymentVoucherView")
                                                  { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("ViewPayment", "Voucher")"><span class="icon16 typ-icon-views"></span>View Record</a>
                                </li>*@

                            <li>
                                <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ReceiptVoucherAdd")
                                          { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("AddReceipt", "Voucher")"><span class="icon16 typ-icon-plus"></span>Receipt Voucher</a>
                            </li>
                            @*<li>
                                    <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ReceiptVoucherView")
                                                  { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("ViewReceipt", "Voucher")"><span class="icon16 typ-icon-views"></span>View Record</a>
                                </li>*@
                        </ul>
                    </li>
                    <li>
                        <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ViewLedgerList")
                                  { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("ViewLedgerList", "Voucher")"><span class="icon16 typ-icon-arrow-down"></span>View Ledger</a>
                    </li>
                    @*<li>
                            <a class="@{if (ViewBag.Title != null || ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView")
                                    { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 icomoon-icon-list-2"></span>Payment Voucher</a>
                            <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "PaymentVoucherAdd" || ViewBag.Title == "PaymentVoucherView"))
                                                 { <text>display: block;</text>    } else { <text></text>    }}">
                                <li>
                                    <a class="@{if (ViewBag.Title != null && ViewBag.Title == "PaymentVoucherView")
                                                  { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("ViewPayment", "Voucher")"><span class="icon16 typ-icon-views"></span>View Record</a>
                                </li>
                            </ul>
                        </li>*@

                </ul>
            </li>

            @*<li>
                <a class="@{if (ViewBag.Title != null || ViewBag.Title == "EntryLoan" || ViewBag.Title == "ViewLoan")
                                { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 cut-icon-equalizer"></span>Loan Entry<span class="hasDrop icon16 icomoon-icon-arrow-down-2"></span></a>
                <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "EntryLoan" || ViewBag.Title == "ViewLoan"))
                                             { <text>display: block;</text>    } else { <text></text>    }}">

                    <li>
                        <a class="@{if (ViewBag.Title != null && ViewBag.Title == "EntryLoan")
                                      { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("Index", "Loan")"><span class="icon16 typ-icon-plus"></span>Add Loan</a>
                    </li>
                    <li>
                        <a class="@{if (ViewBag.Title != null && ViewBag.Title == "ViewLoan")
                                      { <text>current</text>   } else { <text></text>   }}" href="@Url.Action("LoanView", "Loan")"><span class="icon16 typ-icon-arrow-down"></span>View Loan</a>
                    </li>
                </ul>
            </li>*@

            <li>
                <a class="@{if (ViewBag.Title != null || ViewBag.Title == "ReportView")
                                { <text>hasUl</text>   } else { <text></text>   }}" href="#"><span class="icon16 cut-icon-equalizer"></span>Reports<span class="hasDrop icon16 icomoon-icon-arrow-down-2"></span></a>
                <ul class="sub" style="@{if (ViewBag.Title != null && (ViewBag.Title == "ReportView"))
                                             { <text>display: block;</text>    } else { <text></text>    }}">
                    <li>
                        <a class="@{if (ViewBag.Title != null || ViewBag.Title == "ReportView")
                                              { <text>Current</text>   } else { <text></text>   }}" href="@Url.Action("Reports", "Voucher")"><span class="icon16 cut-icon-enter"></span>Reports</a>
                    </li>

                </ul>
            </li>
        </ul>


    </div>
</div>